Feature: Github API 통신 엔드포인트 구현
minturtle/CareerSupport pull request #43
Opened 2024-10-15 12:16 UTC by YeaChan05

## #️⃣연관된 이슈

close #34 

## 📝작업 내용

- Github API를 통한 pr 파일 조회 및 리뷰 기능 구현
  - [org.kohsuke.github-api](https://github-api.kohsuke.org/)를 사용한 코드 구성

### 스크린샷 (선택)
![image](https://github.com/user-attachments/assets/f5b613ed-77ec-4521-bd2a-347e9805557d)

## 💬리뷰 요구사항(선택)
> 응답 속도가 비이상적으로 느린 현상이 있습니다. 혹시 제가 blocking이 된 부분을 제대로 처리하지 않을수도 있으니 면밀히 확인 부탁드립니다.

2024-10-15 12:54 UTC, minturtle requested changes

2024-10-15 12:54 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
Flux.fromStream()을 사용하면 Stream을 toList하지 않고도 Flux를 생성할 수 있는 것으로 알고있습니다!

2024-10-15 12:54 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
제가 flatMapMany를 사용한 적은 없지만, Flux<Flux<ReviewRequest>>와 같이 반환된 코드를 평탄화해서 Flux<ReviewRequest>로 바꾸는 로직이 아닐까하는 생각이 듭니다. 이게 맞다면 collectList는 필요하지 않지 않을까요?

2024-10-15 12:54 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .then();
위 부분도 마찬가지로 collectList는 필요없을 것 같습니다!

2024-10-15 12:54 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +        return Mono.fromCallable(() -> getPullRequest(token, repositoryName, prNumber))
AI로 부터 댓글 문자열을 반환받은 후에, Comment를 업로드하기 위해 다시 PR을 가져오는 것으로 보이는데, 이전 Mono에서 다시 값을 가져오기 위해서 Reactor Context를 사용하기도 합니다. 이를 사용하면 PR 요청 보내는 것을 한번으로 줄일 수 있지 않을까요?

2024-10-15 12:57 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
또 여기서, json 등의 기타 설정파일까지 커멘트를 날리는건 아닌거 같아서, 아래와 같이 파일명으로 한번 필터링 하는건 어떨까요?
```
List<String> whiteListFiles = List.of(".java", ".py", ".js");

Flux.just( ... )
.filter(fileName -> isInWhiteListFile(fileName))

```

2024-10-15 21:45 UTC, YeaChan05 commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
fromStream으로 수정하겠습니다!

2024-10-15 21:46 UTC, YeaChan05 commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
제가 알기로는 일반적인 flatMap과 크게 다르지 않습니다
결국 Mono를 Flux로 변환할때 사용된다고 알고 있습니다
근데 getAiCodeReview에서 매개변수로 `List<ReviewResponse>`를 요구하기 때문에 한번은 변환해줘야 할거 같습니다

2024-10-15 21:47 UTC, YeaChan05 commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
이를 회피하려면 `getAiCodeReview `에서 `Flux<ReviewResponse>`를 매개변수로 전달받도록 할까요?

2024-10-16 00:10 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +                .collectList()
아 그렇군요, 그럼 하나의 메서드에서 flux를 처리하는거보다는 mono나 단순 파일 객체만을 파라미터로 전달하도록 변환하는건 어떨까요?

2024-10-16 14:37 UTC, minturtle commented on src/test/java/org/minturtle/careersupport/codereview/controller/CodeReviewControllerTest.java
## Code Review Checklist - CodeReviewControllerTest.java

**1. 코드 클린 코드 준수**

* **가독성:**
    *  코드 전체적으로 가독성이 떨어지는 부분은 없나요? 
    *  변수명, 함수명이 명확하고 이해하기 쉽게 지정되었는지 확인해주세요.
* **중복 코드:** 동일한 코드가 중복되는 부분이 없나요? 추출하여 재사용 가능한 함수나 클래스로 구성할 수 있는 부분은 없는지 확인해주세요.
* **복잡성 및 효율성:** 코드가 불필요하게 복잡하거나 비효율적인 부분은 없는지 리팩토링의 필요성이 있는지 검토해주세요.

**2. 시간 및 공간 복잡도**

*  제시된 코드만으로는 시간 및 공간 복잡도를 분석하기 어렵습니다. 하지만, 알고리즘의 복잡성을 고려하여 더 효율적인 방법이 있는지 검토해주세요.

**3. 코딩 규칙 및 표준 준수**

*  언어의 권장 베스트 프랙티스(들여쓰기, 공백, 주석 등)를 지키고 있는지 확인해주세요. 

**4. 보안 취약점**

*  코드 분석을 통해 SQL 인젝션, XSS, CSRF 등의 보안 취약점이 없는지 확인해주세요. 특히 사용자 입력을 처리하는 부분에 주의를 기울여야 합니다.

**5. 로그 및 디버깅**

*  로그 레벨이 적절한지, 과도한 로그가 없는지 확인해주세요.
*  오류 발생 시 문제를 쉽게 추적할 수 있는 디버깅 정보가 포함되어 있는지 확인해주세요.

**6. 주석 및 문서화**

*  코드의 기능을 명확하게 설명하는 주석이 적절히 작성되었는지 확인해주세요. 특히 복잡한 로직이나 알고리즘의 경우 주석이 필수적입니다.

2024-10-16 14:37 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/AiCodeReviewClient.java
>  package org.minturtle.careersupport.codereview.service;
## Github 코드 리뷰 결과: AiCodeReviewClient.java

**전반적인 평가:**

코드의 구조적 변경은 크게 문제가 없지만, 몇 가지 부분에서 가독성을 높이고 코드의 효율성을 개선할 여지가 있습니다.

**개선 사항:**

1. **클린 코드:**
    * **변수명 및 함수명:** 
        * `ReviewRequest` 클래스 내 `status` 필드는 `fileStatus`로 변경하는 것이 더 직관적일 수 있습니다.
        * `ReviewResponse` 클래스 내 `reviewContent` 필드는 `aiReviewResult` 또는 `codeReviewResult`와 같이  내용을 명확히 드러내는 이름으로 변경하는 것이 좋습니다.
    * **코드 중복:** `ReviewRequest` 클래스의 `of` 메서드와 `from` 메서드는 기능적으로 유사합니다.  `from` 메서드를 통해  `PullRequestFile`과 `GHPullRequestFileDetail` 두 타입을 모두 처리하는  더욱 일반적인 메서드를 만들 수 있습니다. 
    * **리팩토링:** `ReviewFileStatus` enum은  `ReviewFileStatus`로 변경하여 일관성을 유지해야 합니다.

2. **시간/공간 복잡도:**
    * 코드의 시간/공간 복잡도 분석이 필요합니다. 특히 `getAiCodeReview` 메서드가 어떤 작업을 수행하는지 파악해야 합니다.

3. **코딩 규칙 및 표준:**
    * 코드 스타일 가이드라인을 준수하는지 확인해야 합니다. (예: 들여쓰기, 공백, 주석 등)

4. **보안 취약점:**
    * 코드에서 사용되는 데이터 처리 방식을 검토하여 SQL 인젝션, XSS, CSRF 등의 보안 취약점이 없는지 확인해야 합니다.

5. **로그 및 디버깅:**
    * 로그 레벨과 디버깅 정보의 적절성을 확인해야 합니다.

6. **주석 및 문서화:**
    * 코드의 기능과 의도를 명확하게 설명하는 주석이 충분히 작성되어 있는지 확인해야 합니다. 특히 `getAiCodeReview` 메서드와  `ReviewRequest`, `ReviewResponse` 클래스의 역할에 대한 설명이 필요합니다.



**추가적으로:**

* 코드의 의도를 명확히 하는 코드 주석을 추가하세요. 
* `ReviewRequest`와 `ReviewResponse` 클래스의 상속 관계를 고려하여 더욱 효율적인 설계를 할 수 있는지 검토하세요.
* 코드의 테스트 케이스를 작성하여 코드의 올바른 동작을 검증하는 것이 좋습니다.

2024-10-16 14:37 UTC, minturtle commented on build.gradle
>  	implementation 'org.springframework.boot:spring-boot-starter-aop'
## 코드 리뷰 결과: build.gradle

**현재 코드는 크게 문제가 없지만, 몇 가지 개선 사항을 제안합니다.**

**1. 클린 코드**

* **변수명, 함수명**:  
    * 현재 코드에는 변수나 함수명이 직접적으로 이해하기 어려운 부분이 없습니다. 
    * 하지만,  `google-cloud-logging-logback`과 같이 의존성 이름이 길어 사용자에게 명확한 정보를 전달하지 못할 수 있습니다. 
    * 가능하다면, 의존성 이름을 간략하게 줄이거나, 의미를 더 잘 나타내는 변수명을 사용하는 것을 고려해 보세요.

* **중복 코드**: 
    * 현재 코드에는 중복된 부분이 없습니다.

* **복잡성 및 비효율성**: 
    * 현재 코드는 비교적 간단하고 효율적으로 작성되어 있습니다.

* **오탈자**: 
    * 코드 내 오탈자가 없습니다.

**2. 시간 및 공간 복잡도**

* 현재 코드의 시간 및 공간 복잡도를 분석하기 위해서는 더 많은 코드 컨텍스트가 필요합니다.

**3. 코딩 규칙 및 표준**

* **코딩 규칙 준수**:  
    * 코드는 기본적인 들여쓰기, 공백, 주석 규칙을 준수하고 있습니다. 

**4. 보안 취약점**

* **보안 취약점**: 
    * 현재 코드만으로는 보안 취약점 여부를 판단하기 어렵습니다. 보안 취약점 검사는 전체 시스템 및 컨텍스트를 고려해야 합니다.

**5. 로그 및 디버깅**

* **로그**: 
    * 현재 코드에는 로그 관련 부분이 없습니다. 코드의 실행 상태를 파악하고 문제를 해결하기 위해 적절한 로그를 추가하는 것이 좋습니다.
* **디버깅 정보**: 
    * 현재 코드에는 디버깅 정보가 없습니다. 필요에 따라 디버깅 정보를 추가하여 문제 발생 시 원인 규명을 용이하게 할 수 있습니다.

**6. 주석 및 문서화**

* **주석 및 문서화**: 
    * 현재 코드에는 주석이 부족합니다. 코드의 기능, 의도, 사용 방법 등을 명확하게 설명하는 주석을 추가하여 코드 이해도를 높이는 것이 좋습니다.



**요약**

* 의존성 이름을 명확하게 하거나 간략하게 수정
* 로그 및 디버깅 정보 추가
* 코드 주석을 추가하여 이해도 향상 

**추가적인 팁**

* 코드 주석은 코드의 기능과 의도를 명확하게 설명하는 데 사용해야 합니다.
* 로그 레벨을 적절하게 설정하여 과도한 로그를 방지하고 중요한 정보만 기록해야 합니다.
* 코드를 작성하거나 수정할 때마다 코드 리뷰를 통해 다른 개발자의 의견을 듣는 것이 좋습니다.

2024-10-16 14:37 UTC, minturtle commented on src/main/java/org/minturtle/careersupport/codereview/service/GithubCodeReviewService.java
> +package org.minturtle.careersupport.codereview.service;
## Github 코드 리뷰 결과

**1. 클린 코드**

* **가독성:** 
    * 변수명과 함수명은 이해하기 쉽고 직관적입니다. 
    * 코드 블록 내부의 들여쓰기가 일관되고 깔끔합니다. 
    * 주석이 적절히 사용되어 코드의 의도를 명확하게 전달합니다.
* **중복 코드:**  현재 코드에는 중복되는 부분이 없습니다.
* **복잡성 및 리팩토링:** 코드는 비교적 간결하고 이해하기 쉽습니다. 
    * `postCommentsToPullRequest` 함수 내부의 `pullRequest.createReview()` 부분을 재활용 가능한 메서드로 추출하여 코드를 더욱 명확하게 할 수 있습니다.
* **오탈자:** 발견되지 않았습니다.

**2. 시간 및 공간 복잡도**

* 시간 복잡도:  `Flux.fromIterable(pullRequest.listFiles())` 부분에서 리스트를 순회하며 AI 코드 리뷰를 실행하는 부분이 있습니다. 이 부분의 시간 복잡도는 파일 수에 따라 달라질 수 있습니다. 파일 수가 많을 경우 시간 복잡도가 증가할 수 있습니다.  
    * 파일 수를 줄이거나, 파일 목록을 미리 처리하여 메모리에 저장하는 방법을 고려하여 시간 복잡도를 개선할 수 있습니다.
* 공간 복잡도:  `Flux`를 사용하여 댓글 생성 요청을 처리하는 방식은 공간 복잡도를 효율적으로 관리할 수 있습니다.

**3. 코딩 규칙 및 표준**

* **주석:** 코드의 의도를 명확하게 설명하는 주석이 적절하게 사용되었습니다.
* **변수명, 함수명:**  직관적이고 의미를 잘 전달하는 변수명과 함수명을 사용했습니다.
* **들여쓰기, 공백:**  코딩 스타일 가이드라인에 따라 일관된 들여쓰기와 공백을 사용했습니다.
* **추가적인 점검:** 
    * 프로젝트의 코딩 스타일 가이드라인에 따라 추가적인 점검이 필요할 수 있습니다. 

**4. 보안 취약점**

* 코드에서 보안 취약점이 명확하게 발견되지 않았습니다. 
* 하지만, GitHub 토큰을 사용하는 부분은 보안에 유의해야 합니다. 토큰을 노출되지 않도록 주의하고, 필요한 권한만 부여하는 것이 좋습니다.

**5. 로그 및 디버깅**

* 로그 레벨이 적절하게 설정되어 있는지 확인해야 합니다.
* 오류 발생 시 디버깅 정보를 더 자세히 기록하여 문제 해결을 용이하게 할 수 있습니다.

**6. 주석 및 문서화**

* 코드 내 주석이 적절하게 작성되어 있습니다. 
* 클래스, 함수, 변수 등에 대한 더 자세한 설명을 추가하여 코드 이해도를 높일 수 있습니다.

**요약**

전반적으로 코드는 가독성이 높고, 코딩 규칙을 준수하고 있습니다. 

* `postCommentsToPullRequest` 함수의 코드를 재활용 가능한 메서드로 추출하여 코드를 더욱 명확하게 만들 수 있습니다.
* 파일 수가 많은 경우 시간 복잡도를 개선하기 위해 파일 목록을 미리 처리하는 방법을 고려할 수 있습니다.
* GitHub 토큰을 사용하는 부분은 보안에 유의해야 합니다.

2024-10-16 14:52 UTC, minturtle approved these changes

2024-10-16 14:52 UTC, merged